
addpath( fullfile( pwd, 'Gibbs/' ) )
addpath( fullfile( pwd, 'IsingModel/' ))
addpath( fullfile( pwd, 'MCSampler'))
addpath( fullfile( pwd, 'Metropolis'))
addpath( fullfile( pwd, 'Metropolis-Hastings'))
addpath( fullfile( pwd, 'Models'))
addpath( fullfile( pwd, 'Simulated-annealing'))
addpath( fullfile( pwd, 'SliceSampling'))
addpath( fullfile( pwd, 'TransitionOperator'))
